kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spring-boot-pipeline-claim
  namespace: spring-boot-tst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:

