apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: spring-boot/src/main/jkube
    repoURL: https://github.com/kevbrain/spring-boot.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true