kind: Service
apiVersion: v1
metadata:
  namespace: spring-boot-dev
  name: spring-boot-service
  labels:
    app: spring-boot
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: spring-boot